### ISSUE TITLE
Config to disable water block rain

### ISSUE THREAD

**Issue by Czmbxgit** [ldtteam/waterphysics#1]
Large bodies of water create water blocks ~64 blocks above itself that flow down with physics and pile up, flooding the entire world (tested in superflat). I would appreciate a config that can disable this, because it is very laggy and annoying for play. Ran pack with only this mod (literally just this mod). and it still does it.

https://github.com/ldtteam/waterphysics/assets/126533260/77abb050-8295-428d-921a-d2c406a17244

https://github.com/ldtteam/waterphysics/assets/126533260/28ed6af7-f259-4818-9206-c97471cf7345

**Comment by Raycoms** [comment]
This should not happen at all, seems like a bug.

**Comment by Raycoms** [comment]
Fixed
